### PR TITLE
Feat: V4 enhance session payload and fix security issue

### PR DESCRIPTION
**Pull request by rphlmr**
Hello @mitchelvanbever,

I propose this PR for a 4.0.0.

**Major fix** : security issue (will not explain here because it's not fixed). This is what causing a refactor and some breaking changes

**Breaking changes**
- Remove `user` object from session storage (cookie become too big, causing issues like #15 ). Developers can fetch more user data if they want, by their way in loaders (some clues on /examples)
```javascript
// ❌ before in loader
const session = await supabaseStrategy.checkSession(request, { failureRedirect: '/login' })
return json<LoaderData>({ email: session.user?.email })

// ✅ after in loader
const session = await supabaseStrategy.checkSession(request, { failureRedirect: '/login' })
const { user } = await supabaseClient.auth.api.getUser(session.access_token)
return json<LoaderData>({ email: user?.email })
```
- Add `UserSession` type to reflect this change
```javascript
UserSession = {
  access_token: string,
  refresh_token: string,
  userId: string,
}
````
- Add a new `refreshToken` function to use once in a route handling refresh
```javascript
// app/routes/refresh.tsx OR where you want
import type { LoaderFunction } from 'remix'
import { supabaseStrategy } from '~/auth.server'

export const loader: LoaderFunction = async ({ request }) =>
  await supabaseStrategy.refreshToken(request)
```
- SupabaseStrategy constructor allows to customize the `refreshRoutePath` and `refreshFailureRedirect`
- `checkSession` used in `loader` redirects to `refreshRoutePath` when token expires.
`refreshToken` will redirect to where the request came from
- `checkSession` used in `action` don't redirect when token expires and `refreshToken` can be use to refresh on the fly.
Developper must handle the commit session part (readme)

This 4.0.0 should still handle concurrent refresh token. Could be nice if someone who follow this repo can test 😇
On paper, when multiple `<Outlet />`'s loader trigger `checkSession`, the first one witch trigger a refresh token will throw a redirect and break the call stack.
But i'm note 100% confident since it relates on Remix behaviour 🤷‍♂️

Also added prettier and made an unexpected format on all project (this is why there is so much files ...)

### CODE REVIEW

**Comment by rphlmr** [comment]
https://github.com/mitchelvanbever/remix-auth-supabase/issues/10#issuecomment-1025126987 from @jaPajaap was the best solution ✌️

**Comment by rphlmr** [comment]
> [#10 (comment)](https://github.com/mitchelvanbever/remix-auth-supabase/issues/10#issuecomment-1025126987) from @jaPajaap was the best solution ✌️
> 
> but this PR may not handle
> 
> > in actions if token is expired, just refresh the token, because actions are not called in parallel

Reply to myself, action can now refresh token on the fly.

```javascript
import type { ActionFunction } from 'remix'
import { json } from 'remix'
import { AuthorizationError } from 'remix-auth'
import { sessionStorage, supabaseStrategy } from '~/auth.server'
import { supabaseClient } from '~/supabase'

export const action: ActionFunction = async ({ request }) => {
  let userSession = await supabaseStrategy.checkSession(request)

  if (!userSession) {
    userSession = await supabaseStrategy.refreshToken(request)
  }

  if (!userSession) throw new AuthorizationError()

  // or any function needing user access_token
  const { user } = await supabaseClient.auth.api.getUser(
    userSession.access_token
  )

  // mandatory, more info here :
  // https://remix.run/docs/en/v1/api/remix#using-sessions
  const sessionCookie = await sessionStorage.getSession(
    request.headers.get('Cookie')
  )
  sessionCookie.set(supabaseStrategy.sessionKey, userSession)

  return json(
    { user },
    {
      // ⚠️ please, don't forget me
      headers: {
        'Set-Cookie': await sessionStorage.commitSession(sessionCookie),
      },
    }
  )
}
```

**Comment by cusxio** [comment]
Out of curiosity, why is this PR not merged?

**Comment by mitchelvanbever** [comment]
> Out of curiosity, why is this PR not merged?

Hi @cusxio, thanks for your interest! I have been pre-occupied with a lot of "life" stuff and am still actively trying to take a different route to prevent deprecating this repo. But there are also some additions in here that we'll take along the way once it's ready.

Any specific features you were looking for?

**Comment by cusxio** [comment]
> Any specific features you were looking for?

Initially, I was looking for a solution on how the expired `access_token` is being handled.

This PR seems to have a nice solution of routing the request to `/refresh` to handle the "nested request" scenario.

But after thinking more about it, I've implemented a "promise cache" as below, instead of using a `/refresh` route.

```ts
const refreshAccessTokenCache = new Map();

async function refreshAccessToken(
  refresh_token: string
): ReturnType<GoTrueApi["refreshAccessToken"]> {
  const isRefreshing = refreshAccessTokenCache.has(refresh_token);

  if (!isRefreshing) {
    const promise = supabase
      .auth.api.refreshAccessToken(refresh_token)
      .finally(() => {
        refreshAccessTokenCache.delete(refresh_token);
      });
    refreshAccessTokenCache.set(refresh_token, promise);
  }

  return refreshAccessTokenCache.get(refresh_token);
}
```

**Comment by mitchelvanbever** [comment]
> > Any specific features you were looking for?
> 
> Initially, I was looking for a solution on how the expired `access_token` is being handled.
> 
> This PR seems to have a nice solution of routing the request to `/refresh` to handle the "nested request" scenario.
> 
> But after thinking more about it, I've implemented a "promise cache" as below, instead of using a `/refresh` route.
> 
> const refreshAccessTokenCache = new Map();
> 
> async function refreshAccessToken(
>   refresh_token: string
> ): ReturnType<GoTrueApi["refreshAccessToken"]> {
>   const isRefreshing = refreshAccessTokenCache.has(refresh_token);
> 
>   if (!isRefreshing) {
>     const promise = supabase
>       .auth.api.refreshAccessToken(refresh_token)
>       .finally(() => {
>         refreshAccessTokenCache.delete(refresh_token);
>       });
>     refreshAccessTokenCache.set(refresh_token, promise);
>   }
> 
>   return refreshAccessTokenCache.get(refresh_token);
> }

Thanks for clarifying!

The solution you are providing is actually pretty similair to what I have mind to include in the package. However we also feel that handling a refresh like you are currently doing would be a more robust solution. This strategy is already pretty much crossing the boundaries between what the author of remix-auth feels it should be and it looks like we're running into issues because of not listening and trying to do it all anyways 😝 This also comes from the fact that I feel like without the bells and whistles of handling the refresh, it feels like you have to do most manually anyways. 

Thanks for sharing your solution so it can serve as an example for people running into the same problems for now!

**Comment by mitchelvanbever** [comment]
Thanks for the PR. As discussed will be closing this and creating a seperate PR with just the user changes 👍

**Pull request closed without merging**
